(function(){var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},g="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function k(){k=function(){};g.Symbol||(g.Symbol=ca)}var da=0;function ca(a){return"jscomp_symbol_"+(a||"")+da++}
function l(){k();var a=g.Symbol.iterator;a||(a=g.Symbol.iterator=g.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&ba(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return m(this)}});l=function(){}}function m(a){var b=0;return ea(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ea(a){l();a={next:a};a[g.Symbol.iterator]=function(){return this};return a}
function n(a){if(!(a instanceof Array)){l();var b=a[Symbol.iterator];a=b?b.call(a):m(a);for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function fa(a,b){function c(){}c.prototype=b.prototype;a.P=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}
var p=window.Element.prototype,q=p.matches||p.matchesSelector||p.webkitMatchesSelector||p.mozMatchesSelector||p.msMatchesSelector||p.oMatchesSelector;function r(a,b){if(a&&1==a.nodeType&&b){if("string"==typeof b||1==b.nodeType)return a==b||t(a,b);if("length"in b)for(var c=0,d;d=b[c];c++)if(a==d||t(a,d))return!0}return!1}function t(a,b){if("string"!=typeof b)return!1;if(q)return q.call(a,b);b=a.parentNode.querySelectorAll(b);for(var c=0,d;d=b[c];c++)if(d==a)return!0;return!1}
function ha(a){for(var b=[];a&&a.parentNode&&1==a.parentNode.nodeType;)a=a.parentNode,b.push(a);return b}
function ia(a,b,c){function d(a){var d;if(h.composed&&"function"==typeof a.composedPath)for(var e=a.composedPath(),f=0,x;x=e[f];f++)1==x.nodeType&&r(x,b)&&(d=x);else a:{if((d=a.target)&&1==d.nodeType&&b)for(d=[d].concat(ha(d)),e=0;f=d[e];e++)if(r(f,b)){d=f;break a}d=void 0}d&&c.call(d,a,d)}var e=document,h={composed:!0,B:!0},h=void 0===h?{}:h;e.addEventListener(a,d,h.B);return{j:function(){e.removeEventListener(a,d,h.B)}}}
function ja(a){var b={};if(!a||1!=a.nodeType)return b;a=a.attributes;if(!a.length)return{};for(var c=0,d;d=a[c];c++)b[d.name]=d.value;return b}var ka=/:(80|443)$/,u=document.createElement("a"),v={};
function w(a){a=a&&"."!=a?a:location.href;if(v[a])return v[a];u.href=a;if("."==a.charAt(0)||"/"==a.charAt(0))return w(u.href);var b="80"==u.port||"443"==u.port?"":u.port,b="0"==b?"":b,c=u.host.replace(ka,"");return v[a]={hash:u.hash,host:c,hostname:u.hostname,href:u.href,origin:u.origin?u.origin:u.protocol+"//"+c,pathname:"/"==u.pathname.charAt(0)?u.pathname:"/"+u.pathname,port:b,protocol:u.protocol,search:u.search}}var y=[];
function la(a,b){var c=this;this.context=a;this.v=b;this.f=(this.c=/Task$/.test(b))?a.get(b):a[b];this.b=[];this.a=[];this.g=function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];return c.a[c.a.length-1].apply(null,[].concat(n(b)))};this.c?a.set(b,this.g):a[b]=this.g}function z(a,b,c){a=ma(a,b);a.b.push(c);na(a)}function A(a,b,c){a=ma(a,b);c=a.b.indexOf(c);-1<c&&(a.b.splice(c,1),0<a.b.length?na(a):a.j())}
function na(a){a.a=[];for(var b,c=0;b=a.b[c];c++){var d=a.a[c-1]||a.f.bind(a.context);a.a.push(b(d))}}la.prototype.j=function(){var a=y.indexOf(this);-1<a&&(y.splice(a,1),this.c?this.context.set(this.v,this.f):this.context[this.v]=this.f)};function ma(a,b){var c=y.filter(function(c){return c.context==a&&c.v==b})[0];c||(c=new la(a,b),y.push(c));return c}
function B(a,b,c,d,e,h){if("function"==typeof d){var f=c.get("buildHitTask");return{buildHitTask:function(c){c.set(a,null,!0);c.set(b,null,!0);d(c,e,h);f(c)}}}return C({},a,b)}function oa(a,b){var c=ja(a),d={};Object.keys(c).forEach(function(a){if(!a.indexOf(b)&&a!=b+"on"){var e=c[a];"true"==e&&(e=!0);"false"==e&&(e=!1);a=pa(a.slice(b.length));d[a]=e}});return d}
function qa(a){var b;return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];clearTimeout(b);b=setTimeout(function(){return a.apply(null,[].concat(n(d)))},500)}}function ra(a){function b(){c||(c=!0,a())}var c=!1;setTimeout(b,2E3);return b}var D={};
function sa(a,b){function c(){clearTimeout(e.timeout);e.send&&A(a,"send",e.send);delete D[d];e.A.forEach(function(a){return a()})}var d=a.get("trackingId"),e=D[d]=D[d]||{};clearTimeout(e.timeout);e.timeout=setTimeout(c,0);e.A=e.A||[];e.A.push(b);e.send||(e.send=function(a){return function(b){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];c();a.apply(null,[].concat(n(d)))}},z(a,"send",e.send))}
var C=Object.assign||function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(var d=0,e=c.length;d<e;d++){var h=Object(c[d]),f;for(f in h)Object.prototype.hasOwnProperty.call(h,f)&&(a[f]=h[f])}return a};function pa(a){return a.replace(/[\-\_]+(\w?)/g,function(a,c){return c.toUpperCase()})}var E=function ta(b){return b?(b^16*Math.random()>>b/4).toString(16):"10000000-1000-4000-8000-100000000000".replace(/[018]/g,ta)};
function F(a,b){var c=window.GoogleAnalyticsObject||"ga";window[c]=window[c]||function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];(window[c].q=window[c].q||[]).push(b)};window.gaDevIds=window.gaDevIds||[];0>window.gaDevIds.indexOf("i5iSjo")&&window.gaDevIds.push("i5iSjo");window[c]("provide",a,b);window.gaplugins=window.gaplugins||{};window.gaplugins[a.charAt(0).toUpperCase()+a.slice(1)]=b}var G={I:1,J:2,K:3,L:4,M:5,D:6,F:7,N:8,O:9,C:10},H=Object.keys(G).length;
function I(a,b){a.set("\x26_av","2.4.1");var c=a.get("\x26_au"),c=parseInt(c||"0",16).toString(2);if(c.length<H)for(var d=H-c.length;d;)c="0"+c,d--;b=H-b;c=c.substr(0,b)+1+c.substr(b+1);a.set("\x26_au",parseInt(c||"0",2).toString(16))}
function J(a,b){var c=this;I(a,G.D);window.addEventListener&&(this.a=C({events:["click"],linkSelector:"a, area",shouldTrackOutboundLink:this.shouldTrackOutboundLink,fieldsObj:{},attributePrefix:"ga-"},b),this.b=a,this.f=this.f.bind(this),this.c={},this.a.events.forEach(function(a){c.c[a]=ia(a,c.a.linkSelector,c.f)}))}
J.prototype.f=function(a,b){var c=this;if(this.a.shouldTrackOutboundLink(b,w)){var d=b.getAttribute("href")||b.getAttribute("xlink:href"),e=w(d),e={transport:"beacon",eventCategory:"Outbound Link",eventAction:a.type,eventLabel:e.href},h=C({},this.a.fieldsObj,oa(b,this.a.attributePrefix)),f=B(e,h,this.b,this.a.hitFilter,b,a);if(navigator.sendBeacon||"click"!=a.type||"_blank"==b.target||a.metaKey||a.ctrlKey||a.shiftKey||a.altKey||1<a.which)this.b.send("event",f);else{var aa=function(){window.removeEventListener("click",
aa);if(!a.defaultPrevented){a.preventDefault();var b=f.hitCallback;f.hitCallback=ra(function(){"function"==typeof b&&b();location.href=d})}c.b.send("event",f)};window.addEventListener("click",aa)}}};J.prototype.shouldTrackOutboundLink=function(a,b){a=a.getAttribute("href")||a.getAttribute("xlink:href");b=b(a);return b.hostname!=location.hostname&&"http"==b.protocol.slice(0,4)};J.prototype.remove=function(){var a=this;Object.keys(this.c).forEach(function(b){a.c[b].j()})};F("outboundLinkTracker",J);
function ua(){this.a={}}function va(a,b){(a.a.externalSet=a.a.externalSet||[]).push(b)}ua.prototype.G=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];(this.a[a]=this.a[a]||[]).forEach(function(a){return a.apply(null,[].concat(n(c)))})};var K={},L=!1,M;function N(a,b){b=void 0===b?{}:b;this.a={};this.b=a;this.m=b;this.h=null}fa(N,ua);function O(a,b,c){a=["autotrack",a,b].join(":");K[a]||(K[a]=new N(a,c),L||(window.addEventListener("storage",wa),L=!0));return K[a]}
function P(){if(null!=M)return M;try{window.localStorage.setItem("autotrack","autotrack"),window.localStorage.removeItem("autotrack"),M=!0}catch(a){M=!1}return M}N.prototype.get=function(){if(this.h)return this.h;if(P())try{this.h=Q(window.localStorage.getItem(this.b))}catch(a){}return this.h=C({},this.m,this.h)};N.prototype.set=function(a){this.h=C({},this.m,this.h,a);if(P())try{var b=JSON.stringify(this.h);window.localStorage.setItem(this.b,b)}catch(c){}};
function R(a){a.h={};if(P())try{window.localStorage.removeItem(a.b)}catch(b){}}N.prototype.j=function(){delete K[this.b];Object.keys(K).length||(window.removeEventListener("storage",wa),L=!1)};function wa(a){var b=K[a.key];if(b){var c=C({},b.m,Q(a.oldValue));a=C({},b.m,Q(a.newValue));b.h=a;b.G("externalSet",a,c)}}function Q(a){var b={};if(a)try{b=JSON.parse(a)}catch(c){}return b}var S={};
function T(a,b,c){this.f=a;this.timeout=b||U;this.timeZone=c;this.b=this.b.bind(this);z(a,"sendHitTask",this.b);try{this.c=new Intl.DateTimeFormat("en-US",{timeZone:this.timeZone})}catch(d){}this.a=O(a.get("trackingId"),"session",{hitTime:0,isExpired:!1});this.a.get().id||this.a.set({id:E()})}function xa(a,b,c){var d=a.get("trackingId");return S[d]?S[d]:S[d]=new T(a,b,c)}function V(a){return a.a.get().id}
T.prototype.isExpired=function(a){a=void 0===a?V(this):a;if(a!=V(this))return!0;a=this.a.get();if(a.isExpired)return!0;var b=a.hitTime;return b&&(a=new Date,b=new Date(b),a-b>6E4*this.timeout||this.c&&this.c.format(a)!=this.c.format(b))?!0:!1};T.prototype.b=function(a){var b=this;return function(c){a(c);var d=c.get("sessionControl");c="start"==d||b.isExpired();var d="end"==d,e=b.a.get();e.hitTime=+new Date;c&&(e.isExpired=!1,e.id=E());d&&(e.isExpired=!0);b.a.set(e)}};
T.prototype.j=function(){A(this.f,"sendHitTask",this.b);this.a.j();delete S[this.f.get("trackingId")]};var U=30;function W(a,b){I(a,G.C);window.addEventListener&&(this.b=C({increaseThreshold:20,sessionTimeout:U,fieldsObj:{}},b),this.f=a,this.c=ya(this),this.g=qa(this.g.bind(this)),this.l=this.l.bind(this),this.a=O(a.get("trackingId"),"plugins/max-scroll-tracker"),this.i=xa(a,this.b.sessionTimeout,this.b.timeZone),z(a,"set",this.l),za(this))}
function za(a){100>(a.a.get()[a.c]||0)&&window.addEventListener("scroll",a.g)}
W.prototype.g=function(){var a=document.documentElement,b=document.body,a=Math.min(100,Math.max(0,Math.round(window.pageYOffset/(Math.max(a.offsetHeight,a.scrollHeight,b.offsetHeight,b.scrollHeight)-window.innerHeight)*100))),b=V(this.i);b!=this.a.get().sessionId&&(R(this.a),this.a.set({sessionId:b}));if(this.i.isExpired(this.a.get().sessionId))R(this.a);else if(b=this.a.get()[this.c]||0,a>b&&(100!=a&&100!=b||window.removeEventListener("scroll",this.g),b=a-b,100==a||b>=this.b.increaseThreshold)){var c=
{};this.a.set((c[this.c]=a,c.sessionId=V(this.i),c));a={transport:"beacon",eventCategory:"Max Scroll",eventAction:"increase",eventValue:b,eventLabel:String(a),nonInteraction:!0};this.b.maxScrollMetricIndex&&(a["metric"+this.b.maxScrollMetricIndex]=b);this.f.send("event",B(a,this.b.fieldsObj,this.f,this.b.hitFilter))}};W.prototype.l=function(a){var b=this;return function(c,d){a(c,d);var e={};("object"==typeof c&&null!==c?c:(e[c]=d,e)).page&&(c=b.c,b.c=ya(b),b.c!=c&&za(b))}};
function ya(a){a=w(a.f.get("page")||a.f.get("location"));return a.pathname+a.search}W.prototype.remove=function(){this.i.j();window.removeEventListener("scroll",this.g);A(this.f,"set",this.l)};F("maxScrollTracker",W);var X=E();
function Y(a,b){var c=this;I(a,G.F);document.visibilityState&&(this.a=C({sessionTimeout:U,visibleThreshold:5E3,sendInitialPageview:!1,fieldsObj:{}},b),this.b=a,this.i=document.visibilityState,this.s=null,this.w=!1,this.l=this.l.bind(this),this.f=this.f.bind(this),this.o=this.o.bind(this),this.u=this.u.bind(this),this.c=O(a.get("trackingId"),"plugins/page-visibility-tracker"),va(this.c,this.u),this.g=xa(a,this.a.sessionTimeout,this.a.timeZone),z(a,"set",this.l),window.addEventListener("unload",this.o),
document.addEventListener("visibilitychange",this.f),sa(this.b,function(){if("visible"==document.visibilityState)c.a.sendInitialPageview&&(Z(c,{H:!0}),c.w=!0),c.c.set({time:+new Date,state:"visible",pageId:X,sessionId:V(c.g)});else if(c.a.sendInitialPageview&&c.a.pageLoadsMetricIndex){var a={},a=(a.transport="beacon",a.eventCategory="Page Visibility",a.eventAction="page load",a.eventLabel="(not set)",a["metric"+c.a.pageLoadsMetricIndex]=1,a.nonInteraction=!0,a);c.b.send("event",B(a,c.a.fieldsObj,
c.b,c.a.hitFilter))}}))}
Y.prototype.f=function(){var a=this;if("visible"==document.visibilityState||"hidden"==document.visibilityState){var b=Aa(this),c={time:+new Date,state:document.visibilityState,pageId:X,sessionId:V(this.g)};"visible"==document.visibilityState&&this.a.sendInitialPageview&&!this.w&&(Z(this),this.w=!0);"hidden"==document.visibilityState&&this.s&&clearTimeout(this.s);this.g.isExpired(b.sessionId)?(R(this.c),"hidden"==this.i&&"visible"==document.visibilityState&&(clearTimeout(this.s),this.s=setTimeout(function(){a.c.set(c);
Z(a,{hitTime:c.time})},this.a.visibleThreshold))):(b.pageId==X&&"visible"==b.state&&Ba(this,b),this.c.set(c));this.i=document.visibilityState}};function Aa(a){var b=a.c.get();"visible"==a.i&&"hidden"==b.state&&b.pageId!=X&&(b.state="visible",b.pageId=X,a.c.set(b));return b}
function Ba(a,b,c){c=(c?c:{}).hitTime;var d={hitTime:c},d=(d?d:{}).hitTime;(b=b.time?(d||+new Date)-b.time:0)&&b>=a.a.visibleThreshold&&(b=Math.round(b/1E3),d={transport:"beacon",nonInteraction:!0,eventCategory:"Page Visibility",eventAction:"track",eventValue:b,eventLabel:"(not set)"},c&&(d.queueTime=+new Date-c),a.a.visibleMetricIndex&&(d["metric"+a.a.visibleMetricIndex]=b),a.b.send("event",B(d,a.a.fieldsObj,a.b,a.a.hitFilter)))}
function Z(a,b){var c=b?b:{};b=c.hitTime;var c=c.H,d={transport:"beacon"};b&&(d.queueTime=+new Date-b);c&&a.a.pageLoadsMetricIndex&&(d["metric"+a.a.pageLoadsMetricIndex]=1);a.b.send("pageview",B(d,a.a.fieldsObj,a.b,a.a.hitFilter))}Y.prototype.l=function(a){var b=this;return function(c,d){var e={},e="object"==typeof c&&null!==c?c:(e[c]=d,e);e.page&&e.page!==b.b.get("page")&&"visible"==b.i&&b.f();a(c,d)}};
Y.prototype.u=function(a,b){a.time!=b.time&&(b.pageId!=X||"visible"!=b.state||this.g.isExpired(b.sessionId)||Ba(this,b,{hitTime:a.time}))};Y.prototype.o=function(){"hidden"!=this.i&&this.f()};Y.prototype.remove=function(){this.c.j();this.g.j();A(this.b,"set",this.l);window.removeEventListener("unload",this.o);document.removeEventListener("visibilitychange",this.f)};F("pageVisibilityTracker",Y);})();
//# sourceMappingURL=autotrack.custom.dist.js.map